[package]
name = "native-git"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8", default-features = false, features = ["napi8", "async"] }
napi-derive = "3.5"
gix = { version = "0.80", default-features = false, features = [
  "status",
  "revision",
  "dirwalk",
  "blob-diff",
  "index",
] }
gix-status = "0.27"

[build-dependencies]
napi-build = "2.3"

[profile.release]
lto = "thin"
opt-level = 2
